FROM gkiavash/pangolin:0.0.1

RUN apt-get update && apt-get install -y  \
    python3-dev  \
    python3-numpy \
    libavcodec-dev  \
    libavformat-dev  \
    libswscale-dev \
    libgstreamer-plugins-base1.0-dev  \
    libgstreamer1.0-dev \
    libgtk-3-dev


RUN git clone --branch 4.4.0 https://github.com/opencv/opencv.git
RUN cd opencv && mkdir build
WORKDIR opencv/build
RUN cmake ../
RUN make
RUN make install
